application: djgaeex
version: 1
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: django
  version: "1.4"
  
builtins:
- django_wsgi: on

handlers:
- url: /static/admin
  static_dir: static/admin
  expiration: '0'

 
env_variables:
  DJANGO_SETTINGS_MODULE: 'djgaeex.settings'